# permissions for end users to edit databaseclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclaim-editor-role
rules:
- apiGroups:
  - k8s-db-operator.razzie.github.io
  resources:
  - databaseclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-db-operator.razzie.github.io
  resources:
  - databaseclaims/status
  verbs:
  - get
