# permissions for end users to view databaseclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclaim-viewer-role
rules:
- apiGroups:
  - k8s-db-operator.razzie.github.io
  resources:
  - databaseclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-db-operator.razzie.github.io
  resources:
  - databaseclaims/status
  verbs:
  - get
